# This file contains values from Cookiecutter

default_context:
  project_name: "gcop"
  project_description: "gcop is your local git command copilot"
  organization: "gcop"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "Undertone0809"
  email: "zeeland4work@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
